I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 14, in script call
    call act1_main
  File "game/script.rpy", line 14, in script call
    call act1_main
ScriptError: could not find label 'act1_main'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 14, in script call
    call act1_main
  File "renpy/ast.py", line 1444, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 14, in script call
    call act1_main
  File "renpy/script.py", line 910, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'act1_main'.

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
Tweleve 1.0
Mon Jun 14 23:47:56 2021
